project:
  output-dir: _book

format:
  pdf:
    documentclass: scrreprt
    toc: true
    toc-depth: 2
    execute:
      cache: true
    include-in-header:
      - text: |
          \usepackage{makeidx}
          \makeindex