project:
  type: book
  preview:
    browser: true
book:
  title: An Introduction to Computing and Data for Scientists
  subtitle: With R
  author: Dominic White
  date: today
  chapters:
  - index.qmd
  - src/book/01_intro.qmd
  - part: Basic Topics
    chapters:
    - src/book/02_setup.qmd
    - src/book/03_r_programming_chapter.qmd
    - src/book/04_rmarkdown_chapter.qmd
    - src/book/05_visualization_chapter.qmd
    - src/book/06_wrangling_chapter.qmd
    - src/book/07_ggplot_chapter.qmd
    - src/book/08_eda_chapter.qmd
    - src/book/09_computing_chapter.qmd
    - src/book/10_modeling_chapter.qmd
    - src/book/11_inference_chapter.qmd
  - part: Advanced Topics
    chapters:
    - src/book/14_reproducibility_chapter.qmd
    - src/book/15_loading_data_chapter.qmd
    - src/book/16_more_graphs_chapter.qmd
    - src/book/17_inference_advanced_chapter.qmd
    - src/book/18_modeling_advanced_chapter.qmd
    # 19 Causality
    - src/book/20_simulation_chapter.qmd
    - src/book/21_prediction_chapter.qmd
    - src/book/22_deep_learning_chapter.qmd
    # 23 Concurrent Programming
    # 24 High Performance Computing
  - part: Scientific Data
    chapters: 
    # - src/book/25_images_chapter.qmd
    # - src/book/26_text_chapter.qmd
    # - src/book/27_time_series_chapter.qmd
    # 28 Signal Processing
    - src/book/29_online_data_chapter.qmd
    # - src/book/30_geospatial_chapter.qmd
    # 31 Bioinformatic data
    # 32 Network data
    - src/book/33_databases_chapter.qmd
    # 34 Big data
  - part: Outputs
    chapters:
    - src/book/35_papers_chapter.qmd
    # - src/book/36_webpages_chapter.qmd
    - src/book/37_dashboards_chapter.qmd
    # 38 Apps
    # 39 Software
    # 40 Presentations and posters
  - src/book/references.qmd
  appendices:
  - src/book/A_faqs_appendix.qmd
  - src/book/B_additional_setup_appendix.qmd
bibliography: references.bib
profile:
  group: 
    - [book, website]