project:
  output-dir: docs
  # post-render: # uncomment to put all chapter in top directory
  #   - _flatten_html_output.R

format:
  html:
    theme: cosmo
    css: include/webex.css
    include-after-body: include/webex.js
    execute:
      cache: true
