project:
  output-dir: _book

format:
  pdf:
    documentclass: scrreprt
    toc: true
    toc-depth: 2
    code-block-bg: E9ECEF
    code-block-border-left: B1B4B7
    # execute:
    #   cache: true
    include-in-header:
      - text: |
          \usepackage{makeidx}
          \makeindex
    include-after-body: 
      text: |
        \printindex