project:
  type: book
  preview:
    browser: false
book:
  title: An Introduction to Computing and Data for Scientists
  subtitle: With R
  author: Dominic White
  date: today
  chapters:
  - index.qmd
  - src/book/01_intro.qmd
  - part: Basic Topics
    chapters:
    - src/book/02_setup.qmd
    - src/book/03_r_programming_chapter.qmd
    - src/book/04_rmarkdown_chapter.qmd
    - src/book/05_visualization_chapter.qmd
    - src/book/06_wrangling_chapter.qmd
    - src/book/07_ggplot_chapter.qmd
    - src/book/08_eda_chapter.qmd
    - src/book/09_computing_chapter.qmd
    - src/book/10_modeling_chapter.qmd
    - src/book/11_inference_chapter.qmd
  - part: Advanced Topics
    chapters:
    - src/book/14_reproducibility_chapter.qmd
    - src/book/15_loading_data_chapter.qmd
    # 16 More graphs
    - src/book/17_inference_advanced_chapter.qmd
    - src/book/18_modeling_advanced_chapter.qmd
    # 19 Causality
    # 20 Simulation
    #- src/book/21_prediction_chapter.qmd
    - src/book/22_deep_learning_chapter.qmd
    # 23 Concurrent Programming
    # 24 High Performance Computing
  - part: Scientific Data
    chapters: 
    # 25 Image data
    # 26 Text data
    # 27 Time Series
    # 28 Signal Processing
    # 29 Online data
    # 30 Geospatial data
    # 31 Bioinformatic data
    # 32 Network data
    - src/book/32_databases_chapter.qmd # ->> 33
    # 34 Big data
  # - part: Outputs
    # 35 Papers
    # 36 Webpages
    # 37 Dashboards
    # 38 Apps
    # 39 Software
  - src/book/references.qmd
  appendices:
  - src/book/A_faqs_appendix.qmd
  - src/book/B_additional_setup_appendix.qmd
bibliography: references.bib
profile:
  group: 
    - [book, website]