project:
  output-dir: docs
  post-render: 
    - _copy_assets.R # copies assets folder (TODO: render files also?)
  #   - _flatten_html_output.R # puts all chapters in top directory (needs edits)

format:
  html:
    theme: cosmo
    css: include/webex.css
    include-after-body: include/webex.js
    execute:
      cache: true
