We refer to this combination of the `mapping` parameter and its `aes()` argument as an *aesthetic mapping*, which is a fancy way of saying how we convert columns of the dataset into some visual representation.

But not every part of a graph is determined by data in the dataset. For example, there is no column in the `starwars` dataset that tells us how many bins this histogram should have. Instead we need to specify that number ourselves, with another piece of data (i.e. the number of bins).

Since this number is not in the dataset, it is not an aesthetic mapping. Therefore we specify the number of bins as an argument of the `geom_histogram()` function, and not of the `aes()` function, like so:

```{r, warning=FALSE}
ggplot(data = starwars) +
  geom_histogram(
    mapping = aes(x = height),
    bins = 30
  )
```

Do you see how the `geom_histogram()` function has two parameters, `mapping` and `bins`, whereas the `aes()` function has a single parameter (`x`)?

(We have written the *geom* function's two arguments on separate lines to improve the readability of this code.)

<!-- TODO:
### Histograms with `ggplot()`
Illustrating position and identity
-->
