
<iframe width="560" height="315" src="https://www.youtube.com/embed/VYChbNddUkM?rel=0" frameborder="0" allowfullscreen></iframe>

Slides: [PDF](https://drive.google.com/file/d/1qInq4DXzYsHjmnw2lVu_ffVrAUuzN5ko/view?usp=sharing)

Before we can do any inference, we need to be clear on (1) what data we are using to make our inferences, and (2) what other data those inferences then apply to.

Typically we analyze a **sample** of data (e.g. a group of people, or a series of coin flips). This sample is either:

i. Drawn from a **population** of all possible observations (e.g. our sample of people is drawn from a larger population of people).

ii. Generated by some **random process** (such as flipping a coin).

<!-- TODO: 
add footnote that processes and populations are kind of the same thing 
-->

We then use the sample to make inferences about the population or process.

We also need to distinguish between statistics that we calculate from the sample, and the true value of that statistic from in the total population. If I collect heights from a sample of people, I can then calculate a statistic such as the mean - we would call this the sample mean. However, there is also a population mean that is probably different, since we might have slightly more tall or short people in our sample than in the total population.

When we collect samples, we always hope that our sample is *representative* of the broader population. If it is, then we should be able to make accurate inferences.


### Sampling strategies and how it can go wrong

The best way to create a sample is to first decide what your population is, and then randomly sample members of that population.

If you are interested in the entire population of the USA, for example, then you would want to put every American's name in a (virtual) hat, and then draw a sample of those names.

Of course, there are problems with this! You might not know everyone in your population, and you might not be able to collect data from every member of the sample (for example, it's usually unethical to force people to take part in a survey against their will). 
If your sample is not completely random, then it is unlikely to be representative of the population.

The alternative approach is to start with the sample that you have, and calculate the largest population that we can generalize to. Let's image we measure the heights 100 male students sampled randomly at George Mason University. 

Common sampling biases:
* self-selected
* convenience

Many statistical analyses have gone astray when they generalize to a broader population that they should have done.


### Population-wide censuses

