### "Correlation does not imply causation"

A common saying when working with models is that "correlation does not imply causation". *What does this mean?*

The linear model cannot actually tell us which variable is causing changes in the other (**causation**). Just because we decide to call one variable the "response" and the other "explanatory", does not mean that is necessarily the direction of effect in the real world.

For example, taller people generally weigh more, but there is nothing stopping us from creating a linear model in which height is the response variable (y), even though most people would say that it makes no sense to say that your weight *causes* your height.

Since we have picked which variable is the "response" before creating the linear model, it would be circular for us to then claim that the linear model shows that the explanatory variable is causing the response. Of course it seems to be showing that, because we told it to show it! The linear model (which is fundamentally a fairly simple mathematical formula) has no way of detecting the true causal relationships that exist in the real world.

To summarize in more general terms: even if there seems to be a linear relationship between two variables, we cannot definitively say that one causes the change in the other - only that they are **correlated**.

Even when we have a correlation, it's possible that neither of the variables in your model is directly *causing* a change in the other. There might be other variables (that are not in our model) that actually cause the change in both of the modeled variables. To return to our height vs. weight example: the variation in both height and weight might be caused by diet (or genetics), yet we have not included diet (or genetics) as a variable in our model. Imagine a world in which better^[calorie-caveat] diet causes all of the variation in people's height and weight. A linear model of height and weight would show a strong correlation - however (in this contrived example) neither is causing the changes in the other since both are ultimately being determined by another factor which we have not analyzed.

^[calorie-caveat]: Or, at least, more calorific...

<!--
TODO:
- quiz questions on this
-->