```{r, include=FALSE}
library(tidyverse)
baker_cols <- read_tsv(
  "../data/Baker_2016_Nature_Reproducibilitysurveyrawdata20160523.txt", 
  locale=locale(encoding="latin1"),
  n_max = 2,
  col_names = FALSE
  )
bc_p1 <- baker_cols %>%
  slice(1) %>%
  pivot_longer(cols = everything()) %>%
  fill(value)
bc_p2 <- baker_cols %>%
    slice(2) %>%
    pivot_longer(cols = everything())
baker_col_names <- full_join(bc_p1, bc_p2, by = c("name" = "name")) %>%
  mutate(
    value = if_else(
      is.na(value.y),
      value.x,
      str_c(value.x, ": ", value.y)
    )
  ) %>%
  pluck(4)
baker_survey_df <- read_tsv(
  "../data/Baker_2016_Nature_Reproducibilitysurveyrawdata20160523.txt", 
  col_names = baker_col_names,
  locale=locale(encoding="latin1"),
  skip = 2
  )
```

```{r, include = FALSE}
sum_stat <- baker_survey_df %>%
  select(
    interest = `Which of the following best describes your area of interest?`,
    fail_another = `Which, if any, of the following have you done?: Tried and failed to reproduce someone else's experiment`
  ) %>%
  group_by(
    interest, fail_another
    ) %>%
  summarize(
    n = n(),
    # fail_another = sum(`Which, if any, of the following have you done?: Tried and failed to reproduce someone else's experiment`)
  ) %>%
  ungroup() %>%
  pivot_wider(
    names_from = fail_another,
    values_from = n
  ) %>%
  rowwise() %>% 
  mutate(
    total = sum(No, Yes, `I can't remember`, na.rm=TRUE),
    yeses = Yes
  ) %>%
  pivot_longer(cols = c(No, Yes, `I can't remember`)) %>%
  mutate(
    fraction = value/total,
    yes_fraction = yeses / total
  ) #%>%
  # group_by(interest) %>%
  # mutate(level = )
sum_stat
```

```{r, echo=FALSE, warning=FALSE}
#| label: fig-failed-reproduction-by-discipline
#| fig-cap: "Data from [@baker500ScientistsLift2016]."

sum_stat %>%
  ggplot() +
  geom_col(
    aes(x = reorder(interest, yes_fraction, FUN=mean ), y = 100*fraction, fill=name)
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "top",
    title = element_text(size=9),
    legend.spacing = margin(l= 5, r = 5)
  ) +
  labs(x = "", y = "Percent", title = "1,500 scientists' answers to 'Have you ever tried and failed to reproduce somebody else's experiment?'", fill = "") +
  scale_fill_manual(breaks = c("Yes", "I can't remember", "No"), 
                       values=c("red", "yellow", "green"))
```

