---
html-math-method: 
  method: mathjax
  url: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS-MML_HTMLorMML
execute:
  freeze: false
  cache: false
---

# Introduction to R {#sec-intro-r-programming-chapter}

```{r setup}
#| echo: false
#| results: "asis"

source("prechapter.R")
insert_status_callout("draft")
```


## Your First Program

{{< include ../../src/snippets/r_programming_hello_world.Rmd >}}


## Data

```{r, echo=FALSE, results='asis'}
pdf_dev_comment("TODO: mention scientific notation for large (and small) numbers")
```

{{< include ../../src/snippets/r_programming_data.Rmd >}}


## Operators

{{< include ../../src/snippets/r_programming_operators.Rmd >}}


## Storing and reusing results with *variables*

{{< include ../../src/snippets/r_programming_variables.Rmd >}}


## How R works

```{r, echo=FALSE, results='asis'}
pdf_dev_comment("TODO: Sidebar here about Grace Hopper and the invention of programming languages (plus bugs, Arlington park, and the Queen of Code documentary from 538) ")
```


{{< include ../../src/snippets/r_programming_how_it_works.Rmd >}}


## Boolean data

{{< include ../../src/snippets/r_programming_boolean_data.Rmd >}}


## Vectors

{{< include ../../src/snippets/r_programming_vectors.Rmd >}}


## Functions {#sec-intro-r-functions}

{{< include ../../src/snippets/r_programming_functions.Rmd >}}

```{r, echo=FALSE, results='asis'}
pdf_dev_comment("TODO: Add a section on creating, opening, and saving files in RStudio. Also cover .R source files, and link back from the RMarkdown chapter. Also cover file systems and how to navigate them (Windows and Mac).
")
```


## Packages

{{< include ../../src/snippets/r_programming_packages.Rmd >}}

