---
execute:
  freeze: true
  cache: true
---

# Exploratory Data Analysis and Scientific Discovery

```{r setup, include=FALSE}
source("prechapter.R")
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(ggbrace))
suppressPackageStartupMessages(library(corrr))
```

## What is EDA?

<!--
TODO: References & further reading (Peng book, R4DS, NIST handbook, Seltman book)
      * Peng: https://bookdown.org/rdpeng/exdata/exploratory-data-analysis-checklist.html
      
TODO: Add labels to graphs (mentioned in earlier ggplot chapter)
-->

### Exploratory Data Analysis (EDA)

{{< include ../../src/snippets/eda_intro.Rmd >}}


### Types of variation to explore

{{< include ../../src/snippets/eda_types_of_variation.Rmd >}}


## Starting EDA

{{< include ../../src/snippets/eda_starting_steps.Rmd >}}


### Understand your why

{{< include ../../src/snippets/eda_questions.Rmd >}}


### Understand the dataset

#### Load the data and read the documentation

{{< include ../../src/snippets/eda_load_data.Rmd >}}


#### Get an overview of the data

{{< include ../../src/snippets/eda_glimpse.Rmd >}}


#### Look at the first and last rows of your dataframe

{{< include ../../src/snippets/eda_head_tail.Rmd >}}


#### Make sure that the data makes sense

{{< include ../../src/snippets/eda_sanity_check.Rmd >}}


### Start the EDA cycle

{{< include ../../src/snippets/eda_cycle.Rmd >}}


## Univariate variation

### Non-graphical methods (i.e. summary statistics)

{{< include ../../src/snippets/eda_summary_statistics_univariate.Rmd >}}


### Graphical analysis of `carat`

{{< include ../../src/snippets/eda_carat_variation.Rmd >}}


### `price` visualization

{{< include ../../src/snippets/eda_price_variation_boxplot.Rmd >}}


### Violin plots

{{< include ../../src/snippets/eda_violin_plot.Rmd >}}


### Describing distributions

{{< include ../../src/snippets/eda_describing_distributions.Rmd >}}


## Multivariate covariation

When we have multiple variables, we want to understand how their variation is related: this is called **covariation**.

<!--
### Non-graphical (i.e. summary statistics)
See:
- NIST handbook: https://www.itl.nist.gov/div898/handbook/eda/section3/eda35.htm
- Section 4.4: https://www.stat.cmu.edu/~hseltman/309/Book/chapter4.pdf
- mathematical covariance (and relationship to R-squared) + graphical interpretation with heat map (correlation plot)
-->


### Co-variation with summary statistics

{{< include ../../src/snippets/eda_summary_statistics_multivariate.Rmd >}}


### Visualizing two continuous variables

{{< include ../../src/snippets/eda_covariation_scatter_plot.Rmd >}}


### Visualizing continuous and categorical variables

{{< include ../../src/snippets/eda_covariation_continuous_and_categorical.Rmd >}}


### Visualizing multiple categorical variables

{{< include ../../src/snippets/eda_covariation_dot_plot.Rmd >}}

### The importance of EDA

{{< include ../../src/snippets/eda_anscombes_quartet.Rmd >}}

<!-- TODO:
Also talk about the artefacts and patterns in the diamonds dataset:

* price vs carat in the scatter plots. How this might limit future analyses. Plot a comparison of the best fit line that you would get from diamonds price-size relationship with and without the missing upper part, e.g. two scatter plots side by side with trend lines.
* missing poor color and small diamonds in colored frequency polygons -> highlight possibly "missing" diamonds. How this skewed our box plots to give J diamonds a higher median price!

How it helps to know something about the area of diamonds to interpret these patterns, and thus how data analysis skills are most useful when paired with domain knowledge of the area in question.
-->

## Your turn

<!-- TODO: skip? replace with general book exercises, but omit from tutorial? -->

### Do some EDA

{{< include ../../src/snippets/eda_outro.Rmd >}}

<!-- TODO: Convert outro ^ into an EDA checklist summarizing the previous sections -->


